export const PHYSICAL_COLORS = [
  { name: "Terracotta", hex: "#E2725B", family: "Earth" },
  { name: "Cobalt Blue", hex: "#0047AB", family: "Mineral" },
  { name: "Ochre", hex: "#CC7722", family: "Earth" },
  { name: "Verdigris", hex: "#40826D", family: "Oxide" },
  { name: "Bone White", hex: "#F9F6EE", family: "Organic" },
  { name: "Charcoal", hex: "#36454F", family: "Carbon" },
  { name: "Tyrian Purple", hex: "#66023C", family: "Historic" },
  { name: "Cadmium Yellow", hex: "#FFF600", family: "Pigment" },
  { name: "Slate", hex: "#708090", family: "Stone" },
  { name: "Burnt Sienna", hex: "#E97451", family: "Earth" },
  { name: "Raw Umber", hex: "#826644", family: "Earth" },
  { name: "Crimson", hex: "#DC143C", family: "Organic" },
  { name: "Indigo", hex: "#4B0082", family: "Organic" },
  { name: "Ultramarine", hex: "#120A8F", family: "Mineral" },
  { name: "Viridian", hex: "#40826D", family: "Mineral" },
  { name: "Alizarin", hex: "#E32636", family: "Organic" },
  { name: "Sepia", hex: "#704214", family: "Organic" },
  { name: "Prussian Blue", hex: "#003153", family: "Synthetic" },
  { name: "Emerald", hex: "#50C878", family: "Mineral" },
  { name: "Cerulean", hex: "#007BA7", family: "Sky" },
  { name: "Vermilion", hex: "#E34234", family: "Mineral" },
  { name: "Olive", hex: "#808000", family: "Vegetal" },
  { name: "Sage", hex: "#BCB88A", family: "Vegetal" },
  { name: "Teal", hex: "#008080", family: "Water" },
  { name: "Coral", hex: "#FF7F50", family: "Sea" },
  { name: "Sand", hex: "#C2B280", family: "Earth" },
  { name: "Ash", hex: "#B2BEB5", family: "Fire" },
  { name: "Saffron", hex: "#F4C430", family: "Spice" },
  { name: "Cinnabar", hex: "#E34234", family: "Mineral" },
  { name: "Lapis Lazuli", hex: "#26619C", family: "Stone" },
  { name: "Malachite", hex: "#0BDA51", family: "Stone" },
  { name: "Chartreuse", hex: "#7FFF00", family: "Liquor" },
  { name: "Parchment", hex: "#F1E9D2", family: "Material" },
  { name: "Obsidian", hex: "#0B0B0B", family: "Stone" },
  { name: "Limestone", hex: "#E5D8C5", family: "Stone" },
  { name: "Copper", hex: "#B87333", family: "Metal" },
  { name: "Bronze", hex: "#CD7F32", family: "Metal" },
  { name: "Silver", hex: "#C0C0C0", family: "Metal" },
  { name: "Gold", hex: "#FFD700", family: "Metal" },
  { name: "Rust", hex: "#B7410E", family: "Oxide" }
];